site_name: Yorkitects
site_url: http://yorkitects.github.io/
nav:
  - Home: index.md
  - Contact: contact.md
  - Conceptual Architecture: conceptarchi.md
  - Concrete Architecture: concretarchi.md
theme:
  name: material
  palette:
    scheme: default
    primary: 'black'
    accent: 'white'
